name: 貢獻者清單產生

on:
  push:
    branches:
    - "main"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  Contributors:
    name: 貢獻者清單
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Contributors.yml@main
    with:
      pull_request: "docs/readme"