name: 測試 reusable workflow

on:
  workflow_dispatch:

jobs:
  EnvSetup:
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-env.yml@main

  Debug-Echo:
    runs-on: ubuntu-latest
    needs: EnvSetup
    steps:
      - run: |
          echo 模組包名 ${{ needs.testing.outputs.Modpack_Name }} 
          echo 是否要生成資源包? ${{ needs.testing.outputs.Resourcepack_Patch_Generate }}

  Resourcepack:
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-resourcepack.yml@main
    needs: EnvSetup
    with:
      Modpack_Name: ${{ needs.testing.outputs.Modpack_Name }} 
      Generate: ${{ needs.testing.outputs.Resourcepack_Patch_Generate }}
