name: 自動發布資源包更新

on:
  workflow_dispatch: {}

jobs:
  Simple-Packer:
    name: 簡易資源包發布
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Simple-ResourcePacker.yml@main
    with:
      resourcepack_file_name: "Testing"
      release_title_name: "Testing Release ResourcePack"
      release_body_path: ".github/configs/release_body_pack.md"
      force_include_files: "LICENSE"
      # release_tag:
      # release_update:
      git_version_replacer: true
      # git_version_var:
      generate_time_replacer: true
      # generate_time_var:
