name: 測試 reusable workflow

on:
  workflow_dispatch:

jobs:
  Environment-Setup:
    name: 環境階段
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-environment.yml@main

  Resourcepack-Maker:
    name: 資源包階段
    needs: Environment-Setup
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-resourcepack.yml@main
    with:
      modpack-name: ${{ needs.Environment-Setup.outputs.modpack_name }}
      resourcepack-generate: ${{ needs.Environment-Setup.outputs.resourcepack_patch_generate }}

  Patch-Maker:
    name: 補丁階段
    needs: [ Environment-Setup, Resourcepack-Maker ]
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-resourcepack.yml@main
    with:
      modpack-name: ${{ needs.Environment-Setup.outputs.modpack_name }}
      modpack-version: 1.0
      modpack-array: ${{ matrix.array }}
      modpack-resourcepack: ${{ needs.Environment-Setup.outputs.resourcepack_patch_generate }}
      modpack-mmlp: ${{ needs.Environment-Setup.outputs.download_mmlp }}
      matrix-name: ${{ matrix.name }}

    strategy:
      matrix:
        include:
          - name: Client
            array: ${{ needs.Environment-Setup.outputs.client_patch_array }}
          - name: Server
            array: ${{ needs.Environment-Setup.outputs.server_patch_array }}
