name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  testing:
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-env.yml@main

  test2:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - run: |
          echo 模組包名 ${{ needs.testing.outputs.Modpack_Name }} 
          echo 是否要生成資源包? ${{ needs.testing.outputs.Resourcepack_Patch_Generate }}
