name: 測試 reusable workflow

on:
  workflow_dispatch:

jobs:
  Environment-Setup:
    name: 環境階段
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-env.yml@main

  Resourcepack-Maker:
    name: 資源包階段
    needs: Environment-Setup
    uses: TeamKugimiya/reusable-workflows/.github/workflows/modpack-resourcepack.yml@main
    with:
      modpack-name: ${{ needs.Environment-Setup.outputs.modpack-name }}
      resourcepack-generate: ${{ needs.Environment-Setup.outputs.resourcepack-patch-generate }}
